sudo: required
services:
  - docker

before_install:
  - docker build -t javaxiss/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true javaxiss/react-test npm run test

after_success:
    - docker build -t javaxiss/multi-client ./client
    - docker build -t javaxiss/multi-nginx ./nginx
    - docker build -t javaxiss/multi-server ./server
    - docker build -t javaxiss/multi-worker ./worker
    # log ing to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push those images to docker hub
    - docker push javaxiss/multi-client
    - docker push javaxiss/multi-,ginx
    - docker push javaxiss/multi-server
    - docker push javaxiss/multi-worker